name: todo_list
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  riverpod: ^0.14.0+3
  uuid: ^3.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
